    - name: Add Android Platform & Sign AAB
      env:
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
      run: |
        npx cap add android || true
        npx cap sync android
        if [ -d "android" ]; then
          cd android
          echo "${{ secrets.SIGNING_KEY }}" | base64 --decode > app/keystore.jks
          cd ..
          
          # تشغيل ملف البايثون الخارجي لتعديل الجريدل بأمان
          python3 sign_app.py

          cd android
          chmod +x gradlew
          ./gradlew bundleRelease
        fi
        
